spring:
  jpa:
    open-in-view: false
    hibernate.ddl-auto: validate
    show-sql: false
    properties:
      'hibernate.jdbc.lob.non_contextual_creation': true
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
  liquibase.change-log: classpath:changelog/db.changelog.xml

  # H2 settings
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
         trace: false
         web-allow-others: false
  datasource:
    url: jdbc:h2:mem:super-hero-app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

logging.level:
  io.swagger: info

management.endpoints.web.exposure.include: ['health', 'info' ]
